name: Build and Deploy

on:
  push:
    branches:
      - gh-pages  # Trigger the workflow on push to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby for Jekyll
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Ensure the correct version of Ruby is installed

    # Step 3: Install dependencies with Bundler
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    # Step 4: Build the Jekyll site
    - name: Build Jekyll site
      run: bundle exec jekyll build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # The directory where Jekyll outputs the site
